### ISSUE TITLE
Not working as it should

### ISSUE THREAD

**Issue by ghost** [0xC0FFEEEE/haxtools#2]
Here is some output even after closing and reopen terminal:

bash: /home/agentwhite/.haxtools/.tools/.cmd_hax: line 3: unexpected argument `(' to conditional binary operator
bash: /home/agentwhite/.haxtools/.tools/.cmd_hax: line 3: syntax error near `(u'
bash: /home/agentwhite/.haxtools/.tools/.cmd_hax: line 3: `  if [[ $1 = (update|download) ]]; then'
agentwhite@kali:~$ hax
bash: hax: command not found
agentwhite@kali:~$ sudo hax
[sudo] password for agentwhite: 
sudo: hax: command not found

**Comment by breakfixrepeat** [comment]
Following installation what happens if you run `hax` after restarting your shell but without running with sudo? Running haxtools commands likely won't work with sudo as the `$HOME/.haxtools/.haxrc` file won't be sourced in the root shells .bashrc

Also, out of interest is agentwhite a member of the docker group?

I'll do some testing myself with bash later today on the syntax issue.

**Comment by breakfixrepeat** [comment]
The hax command issue should be resolved.

I suspect the remaining issue you are having is because your user is not in the docker group. Try running `sudo usermod -aG docker $USER`

The issue should then be resolved after logging out and back in again.
